### ISSUE TITLE
用gulp打包项目的时候，有的时候会出现找不到文件夹的问题，为什么呢？？？

### ISSUE THREAD

**Issue by jsong93** [jsong93/myWorld#1]
有的时候是正常的，有的时候就会有这个问题
```shell
PS E:\Practice\myWorld> gulp
[09:31:58] Using gulpfile E:\Practice\myWorld\gulpfile.js
[09:31:58] Starting 'default'...
[09:31:58] Starting 'clean'...
true
[09:31:58] Finished 'clean' after 15 ms
[09:31:58] Starting 'font'...
[09:31:58] Finished 'font' after 4.44 ms
[09:31:58] Starting 'image'...
[09:31:58] Finished 'image' after 2.87 ms
[09:31:58] Starting 'hero'...
[09:31:58] Finished 'hero' after 2.72 ms
[09:31:58] Starting '<anonymous>'...
[09:31:58] Finished '<anonymous>' after 10 ms
[09:31:58] Finished 'default' after 42 ms
[09:31:59] gulp-imagemin: Minified 1 image (saved 68 kB - 32.7%)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, stat 'E:\Practice\myWorld\build\resource\models'
Emitted 'error' event at:
    at Pumpify.EventEmitter.emit (domain.js:454:12)
    at Pumpify.onerror (E:\Practice\myWorld\node_modules\readable-stream\lib\_stream_readable.js:640:52)
    at Pumpify.emit (events.js:189:13)
    at Pumpify.EventEmitter.emit (domain.js:441:20)
    at Pumpify.Duplexify._destroy (E:\Practice\myWorld\node_modules\duplexify\index.js:191:15)
    at E:\Practice\myWorld\node_modules\duplexify\index.js:182:10
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by jsong93** [comment]
每次打包之前，把build目录删除就好了，build是打包后的目录

**Comment by jsong93** [comment]
clean任务之后的下一个任务 加上setTimeout
https://blog.csdn.net/JsongNeu/article/details/90515468
```
gulp.task('font', done => {
  // settimeout build 还没有删除玩就看是 build  会出问题
  setTimeout(() => {
    gulp.src('./css/font/**').pipe(gulp.dest('build/css/font'));
    done();
  }, 2000);
});
```
