### ISSUE TITLE
When I build my project with pulp, sometimes it throw error 'no such file or directory',sometimes done.why???

### ISSUE THREAD

**Issue by jsong93** [jsong93/myWorld#2]
```shell
PS E:\Practice\myWorld> gulp
[09:31:58] Using gulpfile E:\Practice\myWorld\gulpfile.js
[09:31:58] Starting 'default'...
[09:31:58] Starting 'clean'...
true
[09:31:58] Finished 'clean' after 15 ms
[09:31:58] Starting 'font'...
[09:31:58] Finished 'font' after 4.44 ms
[09:31:58] Starting 'image'...
[09:31:58] Finished 'image' after 2.87 ms
[09:31:58] Starting 'hero'...
[09:31:58] Finished 'hero' after 2.72 ms
[09:31:58] Starting '<anonymous>'...
[09:31:58] Finished '<anonymous>' after 10 ms
[09:31:58] Finished 'default' after 42 ms
[09:31:59] gulp-imagemin: Minified 1 image (saved 68 kB - 32.7%)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, stat 'E:\Practice\myWorld\build\resource\models'
Emitted 'error' event at:
    at Pumpify.EventEmitter.emit (domain.js:454:12)
    at Pumpify.onerror (E:\Practice\myWorld\node_modules\readable-stream\lib\_stream_readable.js:640:52)
    at Pumpify.emit (events.js:189:13)
    at Pumpify.EventEmitter.emit (domain.js:441:20)
    at Pumpify.Duplexify._destroy (E:\Practice\myWorld\node_modules\duplexify\index.js:191:15)
    at E:\Practice\myWorld\node_modules\duplexify\index.js:182:10
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by jsong93** [comment]
detele directory of build before run gulp

I modified my gulp task clean

old
```
gulp.task('clean', d => {
  if (checkDir('./build')) {
    gulp.src('./build/').pipe(clean());
  }
  d();
});
```
new
```
gulp.task('clean', d => {
  if (checkDir('./build')) {
    del(['build']);
    // gulp.src('./build/').pipe(clean());
  }
  d();
});
```

**Comment by jsong93** [comment]
And add setTimeout at next task,because clean do not finish

```
gulp.task('font', done => {
  // settimeout build 还没有删除玩就看是 build  会出问题
  setTimeout(() => {
    gulp.src('./css/font/**').pipe(gulp.dest('build/css/font'));
    done();
  }, 2000);
});
```
